export const mockEvents = [
  {
    id: "1",
    title: "AI & Machine Learning Summit 2026",
    date: "Mar 28, 2026",
    location: "San Francisco, CA",
    attendees: 847,
    capacity: 1000,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80",
    status: "live" as const,
    category: "Technology",
    description: "The premier gathering for AI practitioners and researchers. Three days of cutting-edge talks, workshops, and networking.",
  },
  {
    id: "2",
    title: "Design Systems Conference",
    date: "Apr 05, 2026",
    location: "New York, NY",
    attendees: 312,
    capacity: 500,
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&q=80",
    status: "upcoming" as const,
    category: "Design",
    description: "Explore the future of design systems, component libraries, and design-to-code workflows.",
  },
  {
    id: "3",
    title: "Startup Pitch Night: Series A",
    date: "Apr 12, 2026",
    location: "Austin, TX",
    attendees: 200,
    capacity: 200,
    image: "https://images.unsplash.com/photo-1559223607-a43c990c692c?w=600&q=80",
    status: "sold-out" as const,
    category: "Business",
    description: "Watch 12 startups pitch to top-tier VCs. Network with founders and investors.",
  },
  {
    id: "4",
    title: "Cloud Infrastructure Workshop",
    date: "Apr 18, 2026",
    location: "Virtual",
    attendees: 156,
    capacity: 300,
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&q=80",
    status: "upcoming" as const,
    category: "DevOps",
    description: "Hands-on workshop covering Kubernetes, serverless, and edge computing patterns.",
  },
  {
    id: "5",
    title: "Product Management Masterclass",
    date: "Apr 25, 2026",
    location: "London, UK",
    attendees: 89,
    capacity: 150,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80",
    status: "upcoming" as const,
    category: "Product",
    description: "Learn frameworks for product strategy, user research, and roadmap prioritization.",
  },
  {
    id: "6",
    title: "Web3 & Blockchain Forum",
    date: "May 02, 2026",
    location: "Miami, FL",
    attendees: 421,
    capacity: 600,
    image: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&q=80",
    status: "live" as const,
    category: "Technology",
    description: "Deep dive into decentralized systems, smart contracts, and the future of digital ownership.",
  },
];

export const categories = ["All", "Technology", "Design", "Business", "DevOps", "Product"];
